version: "3.9"
services:
  db:
    image: postgres:14.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: "qpsk_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5433:5432"
  
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    links:
      - "db:db"
      - "redis:redis"
    expose:
      - 8001
    ports:
      - "8001:8000"
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
            DATABASE: "postgres"
            DB_DATABASE: "qpsk_db"
            DB_USER: "postgres"
            DB_PASSWORD: "password"
            DB_HOST: "db"
            DB_PORT: "5432"
            CELERY_REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
  
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - server
    networks:
      - default
    ports:
      - "3001:3000"
    links:
      - "server:server"
  
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
  
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    links:
      - "db:db"
      - "redis:redis"
    command: celery -A Qpsk worker -l info
    environment:
            DATABASE: "postgres"
            DB_DATABASE: "qpsk_db"
            DB_USER: "postgres"
            DB_PASSWORD: "password"
            DB_HOST: "db"
            DB_PORT: "5432"
            CELERY_REDIS_URL: "redis://redis:6379"
    depends_on:
      - server
      - redis
  

  
volumes:
    db_data: {}
  
