# Generated by Django 4.2.4 on 2023-08-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('variable', models.CharField(max_length=30)),
                ('default_value', models.FloatField()),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('result', models.JSONField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculation.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResultParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.param')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='calculation.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.resulttype'),
        ),
        migrations.AddField(
            model_name='param',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='calculation.protocol'),
        ),
    ]
