# Generated by Django 4.2.4 on 2023-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
